### ISSUE TITLE
Index页面中显示Post开头而非全文

### ISSUE THREAD

**Issue by AZLisme** [hejianxian/hexo-theme-jane#15]
目前的Index页面中，默认是显示Post的全文的。

有的Post会比较长，翻好久才能看到下一个。能否设置在Index页面中只显示Post开头的部分内容，而不是全文显示呢？

**Comment by hejianxian** [comment]
@AZLisme 

在文本中加一个More标签，这样就只会显示标签之上的内容，相比于设定一个固定显示范围，用More标签会更加灵活。

```html
<!-- more -->
```

**Comment by AZLisme** [comment]
尝试了一下，果然可以！
学习了，十分感谢！
