### ISSUE TITLE
支持你，可以添加文章目录吗

### ISSUE THREAD

**Issue by rosedance** [hejianxian/hexo-theme-jane#19]

**Comment by hejianxian** [comment]
@BlackBeatles 谢谢！ 

“文章目录” 是指在文章详情页里的导航吗？

**Comment by hejianxian** [comment]
@BlackBeatles 

这个一般都是通过hexo插件去现实的。

你可以参考这里： https://hexo.io/zh-cn/docs/helpers.html#toc

```html
<%- toc(str, [options]) %>
```

可能样式和布局需要你自己手动调整。

**Comment by rosedance** [comment]
@hejianxian 好的，还有就是右边的菜单能移动到左边吗？喜欢Ubuntu的风格。多谢

**Comment by hejianxian** [comment]
@BlackBeatles 

你可以看这里 https://github.com/hejianxian/hexo-theme-jane/issues/5
