### ISSUE TITLE
/tags 页面点击标签之后，跳转到了全部的文章列表页

### ISSUE THREAD

**Issue by liyuliang2013** [hejianxian/hexo-theme-jane#22]
执行过命令 hexo new page tags 也不行

**Comment by hejianxian** [comment]
你看看 `source` 文件夹里 是否有一个 `tags` 的文件夹。

**Comment by liyuliang2013** [comment]
是的，有该文件夹
source/tags/
└── index.md

index.md的内容

---
title: tags
date: 2017-09-22 17:18:01
---

**Comment by liyuliang2013** [comment]
http://hejx.space/tags/
你的博客这个页面上的标签，点击任何一个出来的文章数量都不对

**Comment by hejianxian** [comment]
抱歉！这里没有做处理！只是单纯地显示了数量而已。

如果可以的话，欢迎你提交 PR ! 😁

**Comment by xhblovewmy** [comment]
@hejianxian 提交了一个PR，求review
