### ISSUE TITLE
如果快速滚动至底部，下面的内容无法正常显示

### ISSUE THREAD

**Issue by zithan** [hejianxian/hexo-theme-jane#26]
如果快速滚动至底部，下面的内容无法正常显示

**Comment by hejianxian** [comment]
你好，可以截个图吗？还有你的浏览器信息也提供一下。

**Comment by zithan** [comment]
> 第一次打开后，快速滚动至底部，下面的内容再也无法显示
<img width="1280" alt="2018-03-27 16 21 10" src="https://user-images.githubusercontent.com/1336063/37955602-9af57dbe-31db-11e8-93a7-d31b6bc88264.png">

> 双击不显示的空白的地方，就如下图，然后过一会就慢慢显示全部

<img width="1280" alt="2018-03-27 16 23 21" src="https://user-images.githubusercontent.com/1336063/37955626-ad629c02-31db-11e8-88ed-012d1a6945fb.png">

### 浏览器信息如下：

> Google Chrome 已是最新版本
版本 65.0.3325.181（正式版本） （64 位）

*PS : 在safari下是正常的*

**Comment by hejianxian** [comment]
会不会是网速问题？我这边也是这个版本的chrome，并没出现你说的问题。

**Comment by zithan** [comment]
应该是的，直接挂靠github的，是网速问题，谢谢你花时间解答
