### ISSUE TITLE
响应式布局有问题

### ISSUE THREAD

**Issue by peakchen90** [hejianxian/hexo-theme-jane#27]
你好，这个主题非常简约，我非常喜欢。然后使用过程发现一个bug，就是响应式布局有点问题，分辨率宽度在 768 - 838 这个区间会出现横向滚动条，而且右侧导航条会挡住文章内容。
![image](https://user-images.githubusercontent.com/17677589/39391979-266f441c-4adf-11e8-8fa1-2ebcbddf0db5.png)

**Comment by hejianxian** [comment]
谢谢！这个可以麻烦你帮我改一下吗？提个PR什么的 😄
