### ISSUE TITLE
代码块问题

### ISSUE THREAD

**Issue by stonewen** [hejianxian/hexo-theme-jane#3]
markdown里写成这样

```
var a = [];
for (var i = 0; i < 10; i++) {
  a[i] = function () {
    console.log(i);
  };
}
a[6](); // 10
```

在该主题下博客中显示成这样
![image](https://cloud.githubusercontent.com/assets/7484451/13164750/aa4a0424-d6f2-11e5-9b2d-626b232a5b5d.png)

怎样使用可以变成第一种，markdown和hexo初学者

**Comment by hejianxian** [comment]
第一种的意思是 没有左边那个1吗？

**Comment by hejianxian** [comment]
在这里主题里找到这个样式 hexo-theme-jane/source/css/_partial/highlight.styl ，然后你对着页面上的元素，应该是class为gutter这个，然后让它的子元素pre隐藏就好了，然后再调一下左边距离就ok了！

**Comment by stonewen** [comment]
.gutter pre
      @extend $line-numbers
      text-align: right
      padding: 0 10px
      //border-right: 1px solid #ddd
      //margin-right: 10px
      border-radius: 0
    .line
      height: font-size \* line-height
    .gutter pre .line
      display:none
嗯，改成这种达到自己想要的效果了，谢谢了
