### ISSUE TITLE
有些文件是否无效

### ISSUE THREAD

**Issue by qiang** [hejianxian/hexo-theme-jane#4]
非常喜欢楼主的这个简约的主题，但是几个问题想问，在这个文件夹中的scripts文件夹中的文件是否无用。还有Gruntfile.js是干什么用的，能帮我解释下吗？谢谢~

**Comment by hejianxian** [comment]
首先非常感谢您的支持！然后说明一点，就是这个主题我是fork了hexo的默认主题，然后在其基础上修改的，关于你的问题，如下：

1:关于那个scripts里面那个js，其实是把img换成a标签，就是为了满足图片放大的代码规范；
2: Gruntfile.js文件其实是用来初始化项目资源的，都是用来clone资源到source文件夹里，如果你熟悉grunt的话，看代码就明白这是干什么的了。

**Comment by qiang** [comment]
哦，我大体明白了：

至于项目管理工具我就不用关心了，我对Node.js不了解。这个我是可以删除的对吧？
我不知道script中的在代码中的什么地方调用了吗？可可不可删掉（我有点代码洁癖）。
我想既保持Theme的简洁也保证代码能在我的可控范围之内。

**Comment by hejianxian** [comment]
如果你不想要图片放大（fancybox）预览的话，可以删除它！页面对于脚本的引用是在after-footer.ejs里面，你也可以通过配置停用fancybox。
