### ISSUE TITLE
chrome浏览器打开没有右侧的滚动条

### ISSUE THREAD

**Issue by hlx70375** [hejianxian/hexo-theme-jane#9]
chrome浏览器打开没有右侧的滚动条，这样浏览长文章时很不方便。

**Comment by hejianxian** [comment]
这是用css隐藏咯滚动条！你可以去掉这部分的样式！

**Comment by hlx70375** [comment]
我把style.styl和article.styl、highlight.styl黎明的overflow属性都是设置成auto，还是不能显示滚动条。

**Comment by hejianxian** [comment]
在style.sty里面找到

```
::-webkit-scrollbar {
    width: 0px;
}
```

去掉

**Comment by hlx70375** [comment]
好了，谢谢。
还有长文章中文字多，你的css中没有text-align：justify。文字对齐右边参差不起不齐，个人觉得不好看。我自己是加上了。
